language: node_js
node_js: '6'
env:
- CXX=g++-4.8
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
script:
- yarn lint
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: n/rNtNuI5fyqkM5Xn8U5IUXGpcjxAHbtDDm9kw74+dccuRcBa/9rqalHTzZjeUP1aPecPE3O/zBgw3L1nulNtwXIr0Zt57Y4KlhLTsa/mjHvBAynBzp9ls1uaojfGyYLPz+WFxasKc1szTRpOJGH/zDI7laIiI8tLnuhXHPP4Rb7REZgPSsLUP0GeFzHHYIRUC3Ur2hcA6GCo+P2M6RuDP+d1hDBEea/yugLA/w+UPyUeRREVE0kWJOOM+y7zUdVKk+1cJNsR3bl/CG5tScPkG6oWGVFNw/ydsQX8opEzLn9s4djcTv5eHI5WGQpkjy8FTfI88S7q67dQcBXJYjC2KR8iiboHyowGo2ftR4tbjM9VlCsupmPZzDml9VIoy+WKV5jPY32aIHUrAd1EOMtrchPsDqBGiQLrz89pIQysGW8IfJWvrA0i5VfMw9LhelqOY8yI4xZh32OFH1TNF5AKjzHvlJ84KjaYMOfvpH4c1UXCFNKiZl3oGgGD7q+IpId44CrdomR1z5E85h82GZuIagTETDu77yX2QRzod1hxUqWge/Y9AbfKM9IUdXt6t91zYNFkcJcG/6L5L00ylfae0kGrTsMvWXlQLvWUyAqweySKNSaU6FFAfeow39zz8AoGXIHzyhp6WxCJwfuz283vxboljhYK/hMxtgtSDioumQ=
